name: Update Full Resume Gist

on: push

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    environment: ubuntu
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.7

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1.1.4
      with:
        token: ${{ secrets.PAT }}
        gist_id: 5ce10547d2812fced1c74db0ab816b22
        gist_description: "Curriculum Vitae au format JSON Resume — Amaury Van Espen, Data & Solutions Architect. Version base_full outil-agnostique en français, servant de source unique pour les variantes de CV sectorielles (pharma, SAP, conseil, etc.). Contient l'intégralité du parcours : indépendant, Big 4, Défense, consulting SAP/BI, avec 36 compétences, 11 expériences"
        file_path: resume_full.json
